twig:
    file_name_pattern: '*.twig'
    form_themes:
        - 'bootstrap_5_layout.html.twig'
    globals:
        global_vars: '@App\Service\GlobalVars'

when@test:
    twig:
        strict_variables: true
